server:
  port: 4041
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    oracleucp:
      connection-wait-timeout: 60000
      initial-pool-size: 10
      max-pool-size: 100
    password: manager
    type: oracle.ucp.jdbc.PoolDataSourceImpl
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: system
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
